---
title: "Historical Alberta Wildfire Data"
toc: true
toc-depth: 4
toc-location: right
sidebar: false
---

## About the Data

The BC Indigenous Business Listings data set provides a detailed look at Indigenous-owned businesses operating throughout British Columbia. Put together by the Province of British Columbia and shared under the [Open Government Licence - British Columbia](https://www2.gov.bc.ca/gov/content/data/policy-standards/data-policies/open-data/open-government-licence-bc), this data set is a vital resource for understanding Indigenous entrepreneurship in the area.

It includes information such as business names, industries, ownership types, and geographic locations, which offers important insights into economic activities within Indigenous communities. This data set showcases the wide-ranging participation of Indigenous peoples in the economy, bringing attention to communities that have often been overlooked or underrepresented in traditional business directories and economic plans.

By analyzing this data, policymakers, Indigenous economic development organizations, and researchers can spot geographic trends, industry hubs, and recognize gaps in the system. The data set also sheds light on the distribution of Indigenous businesses across various traditional territories, including urban and rural environments and distinguishing between resource-based and service-oriented sectors.

### Download

::: button-container
<a href="../../data/clean/bcindigenousbiz.csv" download class="download-button"> Download CSV </a>
:::

### Metadata

::: description-grid
::: field-label
CSV Name
:::

::: field-value
bcindigenousbiz.csv
:::

::: field-label
Data set Characteristics
:::

::: field-value
Multivariate
:::

::: field-label
Subject Area
:::

::: field-value
Equity and Diversity
:::

::: field-label
Associated Tasks
:::

::: field-value
Classification, Comparative Analysis, Geo spatial Analysis
:::

::: field-label
Feature Type
:::

::: field-value
Categorical, Float, Integer
:::

::: field-label
Instances
:::

::: field-value
1259 records
:::

::: field-label
Features
:::

::: field-value
9
:::

::: field-label
Has Missing Values?
:::

::: field-value
Yes
:::
:::

### Variables

::: table-container
::: styled-table
| Variable Name       | Role    | Type        | Description                                                                     | Units           | Missing Values |
|------------|------------|------------|------------|------------|------------|
| business_name       | Feature | String      | Name of the Indigenous business                                                 | –               | Yes            |
| city                | Feature | String      | City or town where the business is located                                      | –               | Yes            |
| latitude            | Feature | Float       | Latitude coordinate of the business location                                    | Decimal Degrees | Yes            |
| longitude           | Feature | Float       | Longitude coordinate of the business location                                   | Decimal Degrees | Yes            |
| region              | Feature | Categorical | Geographical region of British Columbia where the business operates             | –               | No             |
| type                | Feature | Categorical | Ownership type of the business (e.g., Private, Community Owned, Partnership)    | –               | Yes            |
| industry_sector     | Feature | Categorical | Industry classification based on NAICS or a similar standard                    | –               | Yes            |
| year_formed         | Feature | Numeric     | Year in which the business was established                                      | Year            | Yes            |
| number_of_employees | Feature | Categorical | Size category representing the number of employees (e.g., "1 to 4", "10 to 19") | –               | Yes            |
:::
:::

{{< include ../notebooks/bcindigenousbiz.qmd >}}

## Attribution

Data sourced from the British Columbia Ministry of Jobs, Economic Development and Innovation, available via the Government of British Columbia’s Open Data Catalogue under the [Open Government Licence – British Columbia](https://www2.gov.bc.ca/gov/content/data/policy-standards/data-policies/open-data/open-government-licence-bc). Original data set: [BC IndigenousBusinessListings](https://open.canada.ca/data/en/dataset/bdc81d33-1ab5-4882-9764-8701e8971bb7)
