---
title: "Women's March Madness"
toc: true
toc-depth: 4
toc-location: right
sidebar: false
---

## About the Data

This adapted data set contains historical records of every NCAA Division I Women’s Basketball Tournament appearance since the tournament began in 1982 up until 2018. Sourced from official NCAA, the adapted data set captures tournament results across more than four decades of collegiate women’s basketball. All data is sourced from the NCAA and contains the data behind the story [The Rise and Fall Of Women's NCAA Tournament Dynasties](https://fivethirtyeight.com/features/louisiana-tech-was-the-uconn-of-the-80s/).

The rise in popularity of the NCAA Women’s March Madness, fueled by athletes like Caitlin Clark and Paige Bueckers, reflects a broader cultural shift in the recognition of women’s sports. Beyond entertainment and athletic achievement, women’s participation in sport has social and professional benefits.

As Beth A. Brooke notes in her article [Here’s Why Women Who Play Sports Are More Successful](https://www.linkedin.com/pulse/heres-why-women-who-play-sports-more-successful-brooke-marciniak/), research from EY shows that 94% of women in executive leadership roles played sports, and over half competed at the university level. Participation in sports hel develop skills such as resilience, teamwork, and competitiveness, traits that critical for career success.

Analyzing NCAA Women's March Madness results and promoting visibility of women in sports, beyond exercising our data skills, supports advocation for equity, opportunity, and empowerment of women in leadership.

### Download

<div class="button-container">
  <a href="../../data/clean/womensmarchmadness.csv" download class="download-button">
    Download CSV
  </a>
</div>

### Metadata

<div class="description-grid">
  <div class="field-label">CSV Name</div><div class="field-value">womensmarchmadness.csv</div>
  <div class="field-label">Dataset Characteristics</div><div class="field-value">Multivariate</div>
  <div class="field-label">Subject Area</div><div class="field-value">Women In Sports</div>
  <div class="field-label">Associated Tasks</div><div class="field-value">Regression, Classification</div>
  <div class="field-label">Feature Type</div><div class="field-value">Factor, Integer, Numeric</div>
  <div class="field-label">Instances</div><div class="field-value">2092</div>
  <div class="field-label">Features</div><div class="field-value">20</div>
  <div class="field-label">Has Missing Values?</div><div class="field-value">Yes</div>
</div>

### Variables

::: {.table-container}
::: {.styled-table}

| Variable Name | Role | Type | Description | Units | Missing Values |
|-----|-----|-----|-----|-----|-----|
| year | Feature | integer | Year | - | No |
| school | Feature | nominal categorical | School | - | No |
| seed | Feature | ordinal categorical | Seed. The 0 seeding designation in 1983 notes the eight teams that played an opening-round game to become the No. 8 seed in each region. | - | No |
| conference | Feature | nominal categorical | Conference | - | No |
| conf_wins | Feature | numeric | Conference Wins | - | Yes |
| conf_losses | Feature | numeric | Conference Losses | - | Yes |
| conf_wins_pct | Feature | numeric | Conference Win Percentage | - | Yes |
| conf_rank | Feature | numeric | Place in Conference | - | Yes |
| division | Feature | nominal categorical | Conference Division | - | Yes |
| reg_wins | Feature | integer | Regional Wins | - | No |
| reg_losses | Feature | integer | Regional Losses | - | No |
| reg_wins_pct | Feature | numeric | Regional Win Percentage | % | No |
| bid | Feature | nominal categorical | Whether the school qualified with an automatic bid (by winning its conference or conference tournament) or an at-large bid. ['at-large', 'auto'] | - | No |
| first_game_at_home | Feature | nominal categorical | Whether the school played its first-round tournament games on its home court. ['Y', 'N'] | - | No |
| tourney_wins | Feature | integer | Tourney Wins | - | No |
| tourney_losses | Feature | integer | Tourney Losses | - | No |
| tourney_finish | Target | ordinal categorical | Ordered categories: ['opening_round_loss' < 'first_round_loss' < 'second_round_loss' < 'top_16_loss' < 'top_8_loss' < 'top_4_loss' < 'top_2_loss' < 'champ'] | - | No |
| total_wins | Feature | integer | Total Wins | - | No |
| total_losses | Feature | integer | Total Losses | - | No |
| total_wins_pct | Feature | numeric | Total Win Percentage | % | No |
:::
:::

{{< include ../notebooks/marchmadness.qmd >}}

## Attribution

Data sourced from FiveThirtyEight's NCAA Women's Basketball Tournament dataset, available under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/). Original dataset: [FiveThirtyEight GitHub Repository](https://github.com/fivethirtyeight/data/tree/master/ncaa-womens-basketball-tournament). Story: [Louisiana Tech Was the UConn of the '80s](https://fivethirtyeight.com/features/louisiana-tech-was-the-uconn-of-the-80s/).


Brooke-Marciniak, B. A. (2016, February 7). Here’s why women who play sports are more successful. [LinkedIn article](https://www.linkedin.com/pulse/heres-why-women-who-play-sports-more-successful-brooke-marciniak/).