::: {.hero-banner}

**Diverse Data Hub** is an open educational resource offering curated datasets focused on equity, diversity, inclusion, and other socially relevant topics. It is designed to support students, educators, and researchers in accessing and working with meaningful data in their teaching, learning, and analysis.

Datasets are available through the `diversedata` R package, allowing for straightforward integration into data science workflows. Each dataset includes detailed documentation and contextual background to support informed exploration and connection to real-world topics. Example case studies are also included to illustrate practical applications.

[Get Started →](https://diverse-data-hub.github.io/website_files/datasets.html){.btn .btn-primary}
:::

## Featured Datasets 

:::{.grid-container-3}

<!-- To change featured data set, go into file and change value of data-featured="true". -->

<!-- These are the featured datasets -->

{{< include website_files/grid_items/marchmadness.qmd >}}
{{< include website_files/grid_items/hcmst.qmd >}}

<!-- These are NOT featured datasets -->

{{< include website_files/grid_items/wildfire.qmd >}}
{{< include website_files/grid_items/indigenousbusiness.qmd >}}
{{< include website_files/grid_items/genderassessment.qmd >}}
{{< include website_files/grid_items/globalrights.qmd >}}

:::

## Install `diversedata`

To install the `diversedata` R package from GitHub, follow these steps:

### Prerequisites

- Ensure you have R installed (download from [CRAN](https://cran.r-project.org/))

- Install `devtools` package, if needed:

```r
install.packages("devtools")
```

### Installation

Install `diversedata` directly from GitHub using:

``` r
devtools::install_github("diverse-data-hub/diversedata")
```

### Loading the Package

After installation, load the package into your R session:

``` r
library(diversedata)
```

### Usage

Once installed, you can explore the available data sets and their documentation:

``` r
# List available datasets
data(package = "diversedata")

# View documentation for a specific dataset
?wildfire

# To load a dataset into the environment:
data("wildfire")
```

## License

CC BY 4.0

[Full License](https://github.com/diverse-data-hub/diverse-data-hub.github.io/blob/main/LICENSE)

## Development Team

### Owners

- [Katie Burak PhD](https://github.com/katieburak)
- [Elham E Khoda](https://github.com/elhamekhoda)

### Collaborators

- [Azin Piran](https://github.com/AzinPiran)
- [Francisco Ramirez](https://github.com/fraramfra)
- [Siddarth Subrahmanian](https://github.com/siddart-1)

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const allItems = document.querySelectorAll(".grid-container-3 .grid-item");
    allItems.forEach(item => {
      if (item.dataset.featured === "true") {
        item.style.display = "block";
      } else {
        item.style.display = "none";
      }
    });
  });
</script>