<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Historical Alberta Wildfire Data – Diverse Data Hub</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../website_files/img/favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-d5a90c299ec33309096b483073dacf50.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../website_files/styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Diverse Data Hub</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../website_files/datasets.html"> 
<span class="menu-text">Datasets</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#about-the-data" id="toc-about-the-data" class="nav-link active" data-scroll-target="#about-the-data">About the Data</a>
  <ul>
  <li><a href="#download" id="toc-download" class="nav-link" data-scroll-target="#download">Download</a></li>
  <li><a href="#metadata" id="toc-metadata" class="nav-link" data-scroll-target="#metadata">Metadata</a></li>
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables">Variables</a></li>
  <li><a href="#key-features-of-the-dataset" id="toc-key-features-of-the-dataset" class="nav-link" data-scroll-target="#key-features-of-the-dataset">Key Features of the Dataset</a></li>
  <li><a href="#purpose-and-use-cases" id="toc-purpose-and-use-cases" class="nav-link" data-scroll-target="#purpose-and-use-cases">Purpose and Use Cases</a></li>
  </ul></li>
  <li><a href="#case-study" id="toc-case-study" class="nav-link" data-scroll-target="#case-study">Case Study</a>
  <ul>
  <li><a href="#objective" id="toc-objective" class="nav-link" data-scroll-target="#objective">Objective</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a>
  <ul class="collapse">
  <li><a href="#data-cleaning-processing" id="toc-data-cleaning-processing" class="nav-link" data-scroll-target="#data-cleaning-processing">1. Data Cleaning &amp; Processing</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">2. Exploratory Data Analysis</a></li>
  <li><a href="#logistic-regression-model" id="toc-logistic-regression-model" class="nav-link" data-scroll-target="#logistic-regression-model">3. Logistic Regression Model</a></li>
  <li><a href="#interpretation-of-our-model-using-marginaleffects" id="toc-interpretation-of-our-model-using-marginaleffects" class="nav-link" data-scroll-target="#interpretation-of-our-model-using-marginaleffects">4. Interpretation of our Model <strong>using <code>marginaleffects</code></strong></a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul></li>
  <li><a href="#attribution" id="toc-attribution" class="nav-link" data-scroll-target="#attribution">Attribution</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Historical Alberta Wildfire Data</h1>
</div>



<div class="quarto-title-meta column-page-left">

    
  
    
  </div>
  


</header>


<section id="about-the-data" class="level2">
<h2 class="anchored" data-anchor-id="about-the-data">About the Data</h2>
<p>This dataset contains information on wildfires in Canada, compiled from official government sources under the Open Government Licence – Alberta.</p>
<p>The data was gathered to monitor, assess, and respond to wildfire risks across different regions. Wildfires have far-reaching environmental, social, and economic consequences. From an equity and inclusion perspective, analyzing wildfire data can reveal geographic and resource-based disparities in detection and containment efforts, and highlight how certain populations face greater risks due to climate change and limited infrastructure.</p>
<p>In particular, Alberta experiences some of the most severe and frequent wildfires in Canada due to its vast forested areas, dry climate, and increasing temperatures linked to climate change. Wildfires in Alberta can lead to widespread evacuations, destroy homes and livelihoods, and disproportionately affect rural and Indigenous communities, who may lack access to adequate emergency services and infrastructure. Understanding the patterns of wildfire occurrence and spread helps policymakers, environmental planners, and emergency services allocate resources more equitably and implement effective mitigation strategies. This dataset enables data-driven approaches to reduce the impact of wildfires and support more resilient and inclusive disaster management practices across Alberta and beyond.</p>
<section id="download" class="level3">
<h3 class="anchored" data-anchor-id="download">Download</h3>
<div class="button-container">
<p><a href="../../data/clean/wildfire.csv" download="" class="download-button"> Download CSV </a></p>
</div>
</section>
<section id="metadata" class="level3">
<h3 class="anchored" data-anchor-id="metadata">Metadata</h3>
<div class="description-grid">
<div class="field-label">
DOI
</div>
<div class="field-value">
TBD
</div>
<div class="field-label">
CSV Name
</div>
<div class="field-value">
wildfire.csv
</div>
<div class="field-label">
Dataset Characteristics
</div>
<div class="field-value">
Multivariate
</div>
<div class="field-label">
Subject Area
</div>
<div class="field-value">
Climate Change
</div>
<div class="field-label">
Associated Tasks
</div>
<div class="field-value">
Classification, Time Series, Geospatial Analysis
</div>
<div class="field-label">
Feature Type
</div>
<div class="field-value">
Categorical, Integer
</div>
<div class="field-label">
Instances
</div>
<div class="field-value">
26551 records
</div>
<div class="field-label">
Features
</div>
<div class="field-value">
50
</div>
<div class="field-label">
Has Missing Values?
</div>
<div class="field-value">
Yes
</div>
</div>
</section>
<section id="variables" class="level3">
<h3 class="anchored" data-anchor-id="variables">Variables</h3>
<div class="table-container">
<div class="styled-table">
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 52%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>Variable Name</th>
<th>Role</th>
<th>Type</th>
<th>Description</th>
<th>Units</th>
<th>Missing Values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>year</code></td>
<td>ID</td>
<td>Integer</td>
<td>Year of the wildfire incident</td>
<td>Year</td>
<td>No</td>
</tr>
<tr class="even">
<td><code>fire_number</code></td>
<td>ID</td>
<td>String</td>
<td>Unique identifier for each wildfire</td>
<td>-</td>
<td>No</td>
</tr>
<tr class="odd">
<td><code>current_size</code></td>
<td>Feature</td>
<td>Float</td>
<td>Final estimated size of the wildfire</td>
<td>Hectares</td>
<td>No</td>
</tr>
<tr class="even">
<td><code>size_class</code></td>
<td>Feature</td>
<td>Categorical</td>
<td>Size classification based on fire area</td>
<td>-</td>
<td>No</td>
</tr>
<tr class="odd">
<td><code>latitude</code></td>
<td>Feature</td>
<td>Float</td>
<td>Latitude coordinate of fire origin</td>
<td>Degrees</td>
<td>No</td>
</tr>
<tr class="even">
<td><code>longitude</code></td>
<td>Feature</td>
<td>Float</td>
<td>Longitude coordinate of fire origin</td>
<td>Degrees</td>
<td>No</td>
</tr>
<tr class="odd">
<td><code>fire_origin</code></td>
<td>Metadata</td>
<td>Categorical</td>
<td>General location or region where fire started</td>
<td>-</td>
<td>No</td>
</tr>
<tr class="even">
<td><code>general_cause</code></td>
<td>Feature</td>
<td>Categorical</td>
<td>Broad cause classification of the fire</td>
<td>-</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td><code>responsible_group</code></td>
<td>Metadata</td>
<td>Categorical</td>
<td>Agency or group responsible for managing the fire</td>
<td>-</td>
<td>Yes</td>
</tr>
<tr class="even">
<td><code>activity_class</code></td>
<td>Feature</td>
<td>Categorical</td>
<td>Activity classification at the time of ignition</td>
<td>-</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td><code>true_cause</code></td>
<td>Feature</td>
<td>Categorical</td>
<td>Detailed fire cause (e.g., Arson Known, Hot Exhaust, Line Impact, Unattended Fire, etc.)</td>
<td>-</td>
<td>No</td>
</tr>
<tr class="even">
<td><code>fire_start_date</code></td>
<td>Time</td>
<td>Date</td>
<td>Date the fire started</td>
<td>YYYY-MM-DD</td>
<td>No</td>
</tr>
<tr class="odd">
<td><code>detection_agent_type</code></td>
<td>Feature</td>
<td>Categorical</td>
<td>Type of detection method used (e.g., lookout, patrol, aircraft)</td>
<td>-</td>
<td>No</td>
</tr>
<tr class="even">
<td><code>detection_agent</code></td>
<td>Feature</td>
<td>Categorical</td>
<td>Specific agent who detected the fire</td>
<td>-</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td><code>assessment_hectares</code></td>
<td>Feature</td>
<td>Float</td>
<td>Officially assessed size of the fire</td>
<td>Hectares</td>
<td>No</td>
</tr>
<tr class="even">
<td><code>fire_spread_rate</code></td>
<td>Feature</td>
<td>Float</td>
<td>Rate at which the fire spread</td>
<td>Hectares/hour</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td><code>fire_type</code></td>
<td>Feature</td>
<td>Categorical</td>
<td>Fire behavior classification (e.g., surface, crown, ground)</td>
<td>-</td>
<td>No</td>
</tr>
<tr class="even">
<td><code>fire_position_on_slope</code></td>
<td>Feature</td>
<td>Categorical</td>
<td>Position of the fire on slope (e.g., bottom, mid-slope, ridge)</td>
<td>-</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td><code>weather_conditions_over_fire</code></td>
<td>Feature</td>
<td>Text</td>
<td>Description of weather at the fire location</td>
<td>-</td>
<td>Yes</td>
</tr>
<tr class="even">
<td><code>temperature</code></td>
<td>Feature</td>
<td>Float</td>
<td>Temperature at the fire location</td>
<td>°C</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td><code>relative_humidity</code></td>
<td>Feature</td>
<td>Float</td>
<td>Relative humidity at the fire location</td>
<td>%</td>
<td>Yes</td>
</tr>
<tr class="even">
<td><code>wind_direction</code></td>
<td>Feature</td>
<td>Categorical</td>
<td>Wind direction during the fire</td>
<td>-</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td><code>wind_speed</code></td>
<td>Feature</td>
<td>Float</td>
<td>Wind speed during the fire</td>
<td>km/h</td>
<td>Yes</td>
</tr>
<tr class="even">
<td><code>fuel_type</code></td>
<td>Feature</td>
<td>Categorical</td>
<td>Dominant vegetation or material burned (e.g., grass, timber)</td>
<td>-</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td><code>initial_action_by</code></td>
<td>Metadata</td>
<td>Categorical</td>
<td>Group that initiated suppression efforts</td>
<td>-</td>
<td>Yes</td>
</tr>
<tr class="even">
<td><code>ia_arrival_at_fire_date</code></td>
<td>Time</td>
<td>DateTime</td>
<td>Time when initial action crews arrived</td>
<td>YYYY-MM-DD</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td><code>ia_access</code></td>
<td>Feature</td>
<td>Categorical</td>
<td>Level of access for initial attack teams (e.g., road, helicopter only)</td>
<td>-</td>
<td>Yes</td>
</tr>
<tr class="even">
<td><code>fire_fighting_start_date</code></td>
<td>Time</td>
<td>DateTime</td>
<td>Time when firefighting activities officially started</td>
<td>YYYY-MM-DD</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td><code>fire_fighting_start_size</code></td>
<td>Feature</td>
<td>Float</td>
<td>Fire size at the time firefighting began</td>
<td>Hectares</td>
<td>Yes</td>
</tr>
<tr class="even">
<td><code>bucketing_on_fire</code></td>
<td>Feature</td>
<td>Binary</td>
<td>Whether aerial bucketing was used on the fire</td>
<td>Yes/No</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td><code>first_bh_date</code></td>
<td>Time</td>
<td>DateTime</td>
<td>Date of first blackline containment</td>
<td>YYYY-MM-DD</td>
<td>Yes</td>
</tr>
<tr class="even">
<td><code>first_bh_size</code></td>
<td>Feature</td>
<td>Float</td>
<td>Fire size at time of first blacklining</td>
<td>Hectares</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td><code>first_uc_date</code></td>
<td>Time</td>
<td>DateTime</td>
<td>Date when fire was first declared under control</td>
<td>YYYY-MM-DD</td>
<td>Yes</td>
</tr>
<tr class="even">
<td><code>first_uc_size</code></td>
<td>Feature</td>
<td>Float</td>
<td>Fire size when first declared under control</td>
<td>Hectares</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td><code>first_ex_size_perimeter</code></td>
<td>Feature</td>
<td>Float</td>
<td>Estimated fire perimeter at the time of first extinguishment</td>
<td>Kilometers</td>
<td>Yes</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="key-features-of-the-dataset" class="level3">
<h3 class="anchored" data-anchor-id="key-features-of-the-dataset">Key Features of the Dataset</h3>
<p>Each row represents a single wildfire incident and includes information such as:</p>
<ul>
<li><p><strong>temperature</strong> – The recorded air temperature (°C) at or near the fire location; higher temperatures often increase fire intensity and spread.</p></li>
<li><p><strong>wind_speed</strong> – Speed of wind (km/h) during the fire; stronger winds can accelerate fire spread and complicate suppression.</p></li>
<li><p><strong>relative_humidity</strong> – The percentage of moisture in the air; lower humidity typically increases fire risk by drying out vegetation.</p></li>
<li><p><strong>fire_spread_rate</strong> – The rate at which the fire expanded (e.g., hectares/hour); reflects the fire’s growth dynamics.</p></li>
<li><p><strong>fire_type</strong> – Classification of fire behavior (e.g., surface, crown); influences how fires are managed and controlled.</p></li>
<li><p><strong>fuel_type</strong> – The dominant type of vegetation or material burned (e.g., grass, timber); determines fire intensity and burn characteristics.</p></li>
<li><p><strong>ia_access</strong> – Indicator of how easily suppression crews could access the fire location; limited access can delay response.</p></li>
<li><p><strong>latitude</strong> – Geographic latitude coordinate of the fire’s origin; used for spatial analysis and regional modeling.</p></li>
<li><p><strong>longitude</strong> – Geographic longitude coordinate of the fire’s origin; used alongside latitude for location-specific insights.</p></li>
</ul>
</section>
<section id="purpose-and-use-cases" class="level3">
<h3 class="anchored" data-anchor-id="purpose-and-use-cases">Purpose and Use Cases</h3>
<p>This dataset is designed to support analysis of:</p>
<ul>
<li><p>Factors contributing to the spread, intensity, and size of wildfires</p></li>
<li><p>The impact of weather conditions and fuel types on fire behavior</p></li>
<li><p>Geographic and seasonal patterns in wildfire occurrence</p></li>
<li><p>The effectiveness and timeliness of initial suppression efforts</p></li>
<li><p>Relationships between fire causes, detection methods, and responsible parties</p></li>
</ul>
</section>
</section>
<section id="case-study" class="level2">
<h2 class="anchored" data-anchor-id="case-study">Case Study</h2>
<section id="objective" class="level3">
<h3 class="anchored" data-anchor-id="objective">Objective</h3>
<p>Large wildfires pose serious environmental, social, and economic challenges, especially as climate conditions become more extreme. Identifying the key environmental and human factors linked to these fires can help guide more effective prevention and response strategies.<br>
So, our main question is:</p>
<p><strong>Can we identify the environmental and human factors most associated with large wildfires?</strong></p>
<p>According to <a href="https://cwfis.cfs.nrcan.gc.ca/ha/nfdb">Natural Resources Canada</a>, wildfires exceeding 200 hectares in final size are classified as “large fires.” While these fires represent a small percentage of all wildfires, they account for the majority of the total area burned annually.<br>
The goal is to explore potential predictors of fire size, such as weather, fire cause, and detection method, and provide insights that could inform early interventions and resource planning.</p>
</section>
<section id="analysis" class="level3">
<h3 class="anchored" data-anchor-id="analysis">Analysis</h3>
<p><strong>Loading Libraries</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)         </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggmap)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggspatial)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(maptiles)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data-cleaning-processing" class="level4">
<h4 class="anchored" data-anchor-id="data-cleaning-processing">1. Data Cleaning &amp; Processing</h4>
<ul>
<li>Converted fire size to numeric</li>
<li>Created a binary variable <code>large_fire</code> (TRUE if &gt;200 ha)</li>
<li>Filtered out incomplete records</li>
</ul>
</section>
<section id="exploratory-data-analysis" class="level4">
<h4 class="anchored" data-anchor-id="exploratory-data-analysis">2. Exploratory Data Analysis</h4>
<p><strong>Heat map of Fire Size by Location</strong></p>
<p>The heat map visualizes where wildfires are most concentrated geographically, using latitude and longitude data overlaid on Alberta’s administrative boundaries. The shapefile, retrieved from <a href="https://open.alberta.ca/opendata/legislative-boundaries">Alberta Geospatial Data and Statistics</a>, provides the geographic context needed to highlight wildfire hotspots and identify regions with higher frequency or severity of fire events.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>alberta_shape <span class="ot">&lt;-</span> <span class="fu">suppressMessages</span>(<span class="fu">st_read</span>(<span class="st">"../../data/raw/Alberta_shapefiles/EDS_ENACTED_BILL33_15DEC2017.shp"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `EDS_ENACTED_BILL33_15DEC2017' from data source 
  `C:\Users\Azin\Desktop\Azin files\Azin's Document\UBC\capstone project\diverse-data-hub.github.io\data\raw\Alberta_shapefiles\EDS_ENACTED_BILL33_15DEC2017.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 87 features and 8 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -329155.7 ymin: 5425575 xmax: 365133.5 ymax: 6659344
CRS:           NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(alberta_shape) <span class="ot">&lt;-</span> <span class="dv">3401</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>alberta_shape <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(alberta_shape, <span class="at">crs =</span> <span class="dv">4326</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>wildfire_plot <span class="ot">&lt;-</span> wildfire_clean <span class="sc">|&gt;</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(latitude), <span class="sc">!</span><span class="fu">is.na</span>(longitude), <span class="sc">!</span><span class="fu">is.na</span>(assessment_hectares), assessment_hectares <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>wildfire_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(wildfire_plot, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>), <span class="at">crs =</span> <span class="dv">4326</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>basemap <span class="ot">&lt;-</span> <span class="fu">get_tiles</span>(wildfire_sf, <span class="at">provider =</span> <span class="st">"CartoDB.Positron"</span>, <span class="at">crop =</span> <span class="cn">TRUE</span>, <span class="at">zoom =</span> <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot heatmap</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_spatial</span>(basemap) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_density_2d_filled</span>(</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> wildfire_plot,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> longitude, <span class="at">y =</span> latitude, <span class="at">weight =</span> current_size),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.7</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">contour =</span> <span class="cn">TRUE</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">"turbo"</span>) <span class="sc">+</span>  </span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Fire Size-Weighted Heatmap of Wildfire Locations"</span>,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Longitude"</span>, <span class="at">y =</span> <span class="st">"Latitude"</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="wildfire_files/figure-html/plot_wildfire_size_weighted_heatmap-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Proportion of Large Fires by Cause</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>wildfire_clean <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(true_cause) <span class="sc">|&gt;</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">prop_large =</span> <span class="fu">mean</span>(large_fire, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(prop_large <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(true_cause, prop_large), <span class="at">y =</span> prop_large, <span class="at">fill =</span> prop_large)) <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"skyblue1"</span>, <span class="at">high =</span> <span class="st">"skyblue4"</span>) <span class="sc">+</span>  </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Proportion of Large Fires by True Cause"</span>,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"True Cause"</span>,</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion of Fires &gt; 200 ha"</span>,</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Proportion"</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="wildfire_files/figure-html/plot_proportion_large_fires_by_cause-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="logistic-regression-model" class="level4">
<h4 class="anchored" data-anchor-id="logistic-regression-model">3. Logistic Regression Model</h4>
<p>Governments and emergency planners often care about whether a fire becomes large, not necessarily exactly how large. This makes a binary classification more interpretable and actionable for planning responses. Logistic regression predicts probability of exceeding a threshold, such as “Will this fire exceed 200 hectares?” Modeling the probability of exceeding such a threshold is often more operationally useful than modeling exact hectares.</p>
<p>In <a href="https://wfmrda.nwcg.gov/sites/default/files/docs/WFMRDA/Publications/Decision_Making_Wildfires_rmrs_gtr298.pdf?utm_source=chatgpt.com">Decision Making for Wildfires: A Guide for Applying a Risk Management Process at the Incident Level</a>, the authors outline a risk-based decision-making framework. A key concept is identifying risk thresholds to guide decisions. This aligns with the broader goals of wildfire risk management, which emphasize anticipating fire severity and planning appropriate responses. Logistic regression is well-suited to this context because it models the probability of crossing such thresholds, such as a fire becoming large, enabling a clear, interpretable basis for making timely, risk-informed decisions.</p>
<p>We built a logistic regression model to predict the likelihood of a fire becoming large based on a set of environmental and operational factors that are consistently measurable, statistically significant, and operationally relevant.</p>
<p>In our logistic regression model, we selected key environmental and contextual variables from the <code>wildfire_clean</code> dataset that are well-established drivers of wildfire behavior. These include:</p>
<ul>
<li><p><code>temperature</code>: Higher temperatures increase evaporation, dry out vegetation, and promote ignition and fire spread.</p></li>
<li><p><code>wind_speed</code>: Strong winds feed oxygen to the fire and can carry embers over long distances, accelerating spread.</p></li>
<li><p><code>relative_humidity</code>: Low humidity conditions dry fuels, increasing the probability and intensity of fire ignition.</p></li>
<li><p><code>fire_spread_rate</code>: Reflects how quickly a fire expands; a dynamic indicator of fire behavior.</p></li>
<li><p><code>fire_type</code>: Indicates how the fire behaves (e.g., surface vs.&nbsp;crown fire), which affects controllability and risk.</p></li>
<li><p><code>fuel_type</code>: Different vegetation types burn at different intensities and rates; fuels like grass or timber respond differently under the same conditions.</p></li>
<li><p><code>ia_access</code>: Stands for Initial Attack Access. Limited access can delay suppression efforts, allowing fires to grow larger.</p></li>
</ul>
<p>These variables were chosen because they each represent core determinants of ignition likelihood, fire intensity, and suppression difficulty. As explained in <strong><em>Introduction to Wildland Fire</em></strong> by <strong>Pyne, Andrews, and Laven</strong>, this theoretical foundation supports our inclusion of both meteorological and environmental variables in the model.</p>
<p><strong>Mathematical Definition of the Logistic Regression Model</strong></p>
<p>We aim to estimate the probability that a wildfire becomes large (i.e., burns more than 200 hectares), using logistic regression.</p>
<p>Let:</p>
<p><span class="math display">\[
Y_i =
\begin{cases}
1, &amp; \text{if fire } i \text{ is large (area &gt; 200 ha)} \\
0, &amp; \text{otherwise}
\end{cases}
\]</span></p>
<p><span class="math display">\[
\mathbf{x}_i =
\left(
\text{temperature}_i,
\text{wind\_speed}_i,
\text{relative\_humidity}_i,
\text{fire\_spread\_rate}_i,
\text{fire\_type}_i,
\text{fuel\_type}_i,
\text{ia\_access}_i
\right)
\]</span></p>
<p>Then the model is defined as:</p>
<p><span class="math display">\[
\Pr(Y_i = 1 \mid \mathbf{x}_i) = \frac{1}{1 + \exp(-\eta_i)}
\]</span></p>
<p>where the linear predictor is:</p>
<p><span class="math display">\[
\eta_i = \beta_0
+ \beta_1 \cdot \text{temperature}_i
+ \beta_2 \cdot \text{wind\_speed}_i
+ \beta_3 \cdot \text{relative\_humidity}_i
+ \beta_4 \cdot \text{fire\_spread\_rate}_i
+ \boldsymbol{\beta}_{\text{cat}}^\top \mathbf{x}_{i,\text{cat}}
\]</span></p>
<p>Here:</p>
<p><span class="math display">\[
\begin{aligned}
\beta_0 &amp; \text{ is the intercept} \\
\boldsymbol{\beta}_{\text{cat}} &amp; \text{ is the vector of coefficients for the categorical predictors} \\
\mathbf{x}_{i,\text{cat}} &amp; \text{ is the vector of dummy variables representing those categorical predictors}
\end{aligned}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  large_fire <span class="sc">~</span> temperature <span class="sc">+</span> wind_speed <span class="sc">+</span> relative_humidity <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    fire_spread_rate <span class="sc">+</span> fire_type <span class="sc">+</span> fuel_type <span class="sc">+</span> ia_access,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> wildfire_clean,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>tidy_model <span class="ot">&lt;-</span> <span class="fu">tidy</span>(model) <span class="sc">|&gt;</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">estimate =</span> <span class="fu">round</span>(estimate, <span class="dv">3</span>),</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">std.error =</span> <span class="fu">round</span>(std.error, <span class="dv">3</span>),</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">statistic =</span> <span class="fu">round</span>(statistic, <span class="dv">2</span>),</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">p.value =</span> <span class="fu">round</span>(p.value, <span class="dv">4</span>)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(tidy_model</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>      , <span class="at">caption =</span> <span class="st">"Logistic Regression Results: Predicting Large Fires (&gt; 200 ha)"</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>, <span class="st">"responsive"</span>), <span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Logistic Regression Results: Predicting Large Fires (&gt; 200 ha)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-2.016</td>
<td style="text-align: right;">0.401</td>
<td style="text-align: right;">-5.03</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">temperature</td>
<td style="text-align: right;">0.048</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">4.66</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wind_speed</td>
<td style="text-align: right;">0.050</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">11.03</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">relative_humidity</td>
<td style="text-align: right;">-0.031</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">-7.64</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fire_spread_rate</td>
<td style="text-align: right;">0.104</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">10.30</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">fire_typeGround</td>
<td style="text-align: right;">-1.354</td>
<td style="text-align: right;">0.184</td>
<td style="text-align: right;">-7.37</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fire_typeSurface</td>
<td style="text-align: right;">-1.093</td>
<td style="text-align: right;">0.129</td>
<td style="text-align: right;">-8.48</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">fire_typeUnknown</td>
<td style="text-align: right;">-13.012</td>
<td style="text-align: right;">3683.753</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.9972</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fuel_typeC2</td>
<td style="text-align: right;">-0.945</td>
<td style="text-align: right;">0.175</td>
<td style="text-align: right;">-5.40</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">fuel_typeC3</td>
<td style="text-align: right;">-1.024</td>
<td style="text-align: right;">0.276</td>
<td style="text-align: right;">-3.71</td>
<td style="text-align: right;">0.0002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fuel_typeC4</td>
<td style="text-align: right;">0.454</td>
<td style="text-align: right;">0.337</td>
<td style="text-align: right;">1.35</td>
<td style="text-align: right;">0.1775</td>
</tr>
<tr class="even">
<td style="text-align: left;">fuel_typeC6</td>
<td style="text-align: right;">-16.192</td>
<td style="text-align: right;">4492.954</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.9971</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fuel_typeC7</td>
<td style="text-align: right;">-16.211</td>
<td style="text-align: right;">1258.218</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">0.9897</td>
</tr>
<tr class="even">
<td style="text-align: left;">fuel_typeD1</td>
<td style="text-align: right;">-16.322</td>
<td style="text-align: right;">274.554</td>
<td style="text-align: right;">-0.06</td>
<td style="text-align: right;">0.9526</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fuel_typeM1</td>
<td style="text-align: right;">-1.798</td>
<td style="text-align: right;">0.362</td>
<td style="text-align: right;">-4.97</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">fuel_typeM2</td>
<td style="text-align: right;">-2.272</td>
<td style="text-align: right;">0.279</td>
<td style="text-align: right;">-8.13</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fuel_typeM3</td>
<td style="text-align: right;">-15.610</td>
<td style="text-align: right;">3734.948</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.9967</td>
</tr>
<tr class="even">
<td style="text-align: left;">fuel_typeM4</td>
<td style="text-align: right;">-15.179</td>
<td style="text-align: right;">6522.639</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.9981</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fuel_typeO1a</td>
<td style="text-align: right;">-2.912</td>
<td style="text-align: right;">0.289</td>
<td style="text-align: right;">-10.08</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">fuel_typeO1b</td>
<td style="text-align: right;">-3.514</td>
<td style="text-align: right;">0.456</td>
<td style="text-align: right;">-7.70</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fuel_typeS1</td>
<td style="text-align: right;">-2.189</td>
<td style="text-align: right;">0.486</td>
<td style="text-align: right;">-4.51</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">fuel_typeS2</td>
<td style="text-align: right;">-2.242</td>
<td style="text-align: right;">0.546</td>
<td style="text-align: right;">-4.11</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fuel_typeUnknown</td>
<td style="text-align: right;">-4.148</td>
<td style="text-align: right;">0.481</td>
<td style="text-align: right;">-8.62</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">ia_accessGround</td>
<td style="text-align: right;">-0.861</td>
<td style="text-align: right;">0.410</td>
<td style="text-align: right;">-2.10</td>
<td style="text-align: right;">0.0356</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ia_accessHover Exit</td>
<td style="text-align: right;">-0.083</td>
<td style="text-align: right;">0.412</td>
<td style="text-align: right;">-0.20</td>
<td style="text-align: right;">0.8407</td>
</tr>
<tr class="even">
<td style="text-align: left;">ia_accessRappel</td>
<td style="text-align: right;">-14.797</td>
<td style="text-align: right;">554.243</td>
<td style="text-align: right;">-0.03</td>
<td style="text-align: right;">0.9787</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ia_accessUnknown</td>
<td style="text-align: right;">0.428</td>
<td style="text-align: right;">0.107</td>
<td style="text-align: right;">3.99</td>
<td style="text-align: right;">0.0001</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Higher wind speed (0.050, <em>p</em> &lt; 0.001), temperature (0.048, <em>p</em> &lt; 0.001), and fire spread rate (0.104, <em>p</em> &lt; 0.001) significantly increase the odds of a large wildfire, while relative humidity (-0.031, <em>p</em> &lt; 0.001) decreases it. Compared to crown fires, ground fires (-1.354, <em>p</em> &lt; 0.001) and surface fires (-1.093, <em>p</em> &lt; 0.001) are much less likely to result in large fires.</p>
<p>This logistic regression model estimates the factors influencing the likelihood of a large wildfire. Higher temperature, wind speed, and fire spread rate significantly increase the odds of a large fire, while higher relative humidity decreases it. Certain fire types (e.g., Ground, Surface) and fuel types (e.g., M1, M2, O1a, O1b) are associated with significantly lower odds compared to their respective reference categories. The model shows that higher wind speed, lower humidity, and faster fire spread significantly increase the risk of large wildfires.</p>
<p>Let’s dig into our model further by examining how different environmental and operational factors interact to influence fire outcomes.</p>
</section>
<section id="interpretation-of-our-model-using-marginaleffects" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-of-our-model-using-marginaleffects">4. Interpretation of our Model <strong>using <code>marginaleffects</code></strong></h4>
<p><strong>The Role of Wind Across Fire Causes</strong></p>
<p>As you’ve likely noticed, we did not include <code>true_cause</code> as a predictor in our logistic regression model because it contains many categories, some of which have very few observations. This can lead to large standard errors, unstable coefficient estimates, and a higher risk of overfitting.</p>
<p>However, <code>true_cause</code> remains an important variable for exploratory analysis. Certain ignition causes may be more sensitive to wind. For example, sparks from power lines can spread quickly in high winds, embers from debris burning can travel farther, and unattended fires can escalate rapidly under windy conditions. We chose wind speed for this analysis because it is a well-documented environmental amplifier of fire behavior particularly when interacting with certain ignition causes.</p>
<p>Given these interactions, it’s valuable to visualize and investigate how the effect of wind speed on large wild fire development varies across different causes. Let’s explore this further through faceted marginal effect plots.</p>
<p>This plot shows how wind speed affects the probability of a large wildfire, and how that effect varies across different true causes of fire.</p>
<ul>
<li><p>The x-axis shows the different values of <code>true_cause</code> (fire ignition source categories).</p></li>
<li><p>The y-axis shows the marginal effect of wind speed on the predicted probability (i.e., on the response scale) of a fire becoming large.</p></li>
</ul>
<p>The plot helps us compare the sensitivity of different fire causes to wind speed. For example, if one cause shows a higher marginal effect, it means that increasing wind speed has a stronger impact on the likelihood of large fires for that cause.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">plot_comparisons</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  model,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="st">"wind_speed"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="st">"true_cause"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"response"</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">rep</span>(<span class="st">"darkgreen"</span>, <span class="fu">length</span>(<span class="fu">unique</span>(p<span class="sc">$</span>data<span class="sc">$</span>by)))) <span class="sc">+</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">rep</span>(<span class="st">"darkgreen"</span>, <span class="fu">length</span>(<span class="fu">unique</span>(p<span class="sc">$</span>data<span class="sc">$</span>by)))) <span class="sc">+</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Effect of Wind Speed on Large Fire Probability by True Cause"</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"True Cause"</span>,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Marginal Effect of Wind Speed"</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="wildfire_files/figure-html/plot_marginal_effects_wind_by_cause-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The marginal effects analysis suggests that wind speed may have a relatively stronger impact on the probability of a fire becoming large when the ignition cause is related to Unknown, Insufficient Buffer, Incendiary Device, Hot Exhaust, or Line Impact. However, the overall changes in predicted probabilities are quite small, and the error bars across causes show substantial overlap. This indicates a high degree of uncertainty and suggests that these differences should be interpreted with caution. While the findings may not yet be strong enough to inform operational decisions, they do highlight areas for further exploration. In particular, when wind is forecasted in regions with a history of certain ignition causes, fire managers could use this exploratory insight to guide risk monitoring strategies, while recognizing that more robust evidence is needed before drawing firm conclusions.</p>
<p><strong>Interaction Effects via Marginal Effects</strong></p>
<p>We can also use marginal effects to explore interactions without explicitly adding them to the model, by conditioning on another variable.</p>
<p>This plot shows the marginal effect of <code>relative_humidity</code> on the predicted probability of large fire, calculated separately for each level of <code>fire_type</code>, based on your fitted model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_comparisons</span>(model, <span class="at">variables =</span> <span class="st">"relative_humidity"</span>, <span class="at">by =</span> <span class="st">"fire_type"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="wildfire_files/figure-html/plot_marginal_effects_humidity_by_fire_type-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>When comparing the marginal effect of relative humidity across fire types, we found that three fire types showed almost no change in large fire probability as humidity increased. However, one fire type exhibited a noticeably stronger negative effect. This suggests that humidity plays a more meaningful role in suppressing fire growth for certain fire types likely those that are more sensitive to moisture availability, such as crown fires—while having minimal effect on others.</p>
</section>
</section>
<section id="discussion" class="level3">
<h3 class="anchored" data-anchor-id="discussion">Discussion</h3>
<p>This analysis aimed to uncover the key environmental and operational factors associated with the development of large wildfires in Alberta. Using logistic regression and marginal effects, we modeled the probability of a wildfire exceeding 200 hectares, which is a meaningful operational threshold for fire managers.</p>
<p>We found that higher temperature, stronger wind speed, and faster spread rates significantly increase the likelihood of a large wildfire. Conversely, higher relative humidity consistently reduced fire size probability, highlighting its protective role in fire suppression.</p>
<p>In addition to main effects, we explored interaction patterns using marginal effects. While we did not include <code>true_cause</code> directly in the model due to its high cardinality and sparse categories, we used it in conjunction with <code>wind_speed</code> to explore how ignition causes might modulate wind’s influence on fire growth. The marginal effect plots suggest that certain causes—such as incendiary devices, line impacts, or insufficient buffer zones are more sensitive to wind speed, potentially due to the nature of how these fires spread under wind-driven conditions.</p>
<p>Similarly, by plotting the effect of <code>relative_humidity</code> across different <code>fire_type</code> categories, we observed that humidity suppresses large fire development more strongly in certain fire types, particularly crown fires. This implies that moisture-based mitigation strategies may be more effective in forests prone to crown fire behavior, while having less impact on surface or ground fires.</p>
<p>While some observed differences in marginal effects were small in magnitude and had overlapping confidence intervals, these nuanced insights still provide value. They highlight where future research or localized fire management protocols could focus, especially under climate scenarios with increasing temperature and wind extremes.</p>
<p>Overall, this case study illustrates how statistical modeling paired with domain-informed exploratory tools like marginal effects can support risk-informed, data-driven wildfire management.</p>
</section>
</section>
<section id="attribution" class="level2">
<h2 class="anchored" data-anchor-id="attribution">Attribution</h2>
<p>Data sourced from the Government of Alberta via the Government of Canada’s Open Government Portal, available under an <a href="https://open.alberta.ca/licence">Open Government Licence - Alberta</a>. Original dataset: <a href="https://open.canada.ca/data/en/dataset/a221e7a0-4f46-4be7-9c5a-e29de9a3447e">Historical wildfire data: 2006-2024</a>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This page is built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>