{
  "hash": "9689a06e08863d084ec66396f54392b5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Global Rights Data\"\ntoc: true\ntoc-depth: 4\ntoc-location: right\nsidebar: false\n---\n\n\n\n## About the Data\n\nThis dataset provides yearly, country-level information on LGBTQ+ rights, economic indicators, and education spending. The data is compiled from Our World in Data, with primary sources including Equaldex, the World Bank, and other open-access datasets.\n\n\n\n### Download\n\n<div class=\"button-container\">\n  <a href=\"../../data/clean/globalrights.csv\" download class=\"download-button\">\n    Download CSV\n  </a>\n</div>\n\n### Metadata\n\n<div class=\"description-grid\">\n  <div class=\"field-label\">DOI</div><div class=\"field-value\">TBD</div>\n  <div class=\"field-label\">CSV Name</div><div class=\"field-value\">globalrights.csv</div>\n  <div class=\"field-label\">Dataset Characteristics</div><div class=\"field-value\">Multivariate, Panel (Country-Year)</div>\n  <div class=\"field-label\">Subject Area</div><div class=\"field-value\">Human Rights, Public Policy, International Development</div>\n  <div class=\"field-label\">Associated Tasks</div><div class=\"field-value\">Classification, Regression, Comparative Analysis</div>\n  <div class=\"field-label\">Feature Type</div><div class=\"field-value\">Categorical, Float, Integer</div>\n  <div class=\"field-label\">Instances</div><div class=\"field-value\">2,184 country-year observations (91 countries × 24 years)</div>\n  <div class=\"field-label\">Features</div><div class=\"field-value\">10</div>\n  <div class=\"field-label\">Has Missing Values?</div><div class=\"field-value\">Yes</div>\n</div>\n\n\n### Variables\n\n::: {.table-container}\n::: {.styled-table}\n\n\n| Variable Name              | Role     | Type        | Description                                                                                 | Units          | Missing Values |\n|---------------------------|----------|-------------|---------------------------------------------------------------------------------------------|----------------|----------------|\n| `year`                    | ID       | Integer     | Year the data was recorded                                                                  | Year           | No             |\n| `country`                 | ID       | String      | Country name                                                                                | -              | No             |\n| `country-code`            | ID       | String      | ISO 3-letter country code                                                                   | -              | No             |\n| `gdp-per-capita`          | Feature  | Float       | Gross Domestic Product per capita                                                           | International $| Yes            |\n| `education-spending-gdp` | Feature  | Float       | Government education spending as a percentage of GDP                                        | %              | Yes            |\n| `same-sex-marriage`       | Target   | Categorical | Legal status of same-sex marriage (e.g., Legal, Civil Union, Not Recognized)               | -              | No             |\n| `lgbtq-censorship`        | Feature  | Categorical | Whether LGBTQ+ content is censored or restricted                                            | -              | Yes            |\n| `employment-discrimination` | Feature | Categorical | Whether anti-discrimination protections exist for LGBTQ+ individuals in employment          | -              | Yes            |\n| `gender-affirming-care`   | Feature  | Categorical | Availability and legal access to gender-affirming healthcare                                | -              | Yes            |\n| `legal-gender`            | Feature  | Categorical | Whether legal gender can be changed and under what conditions (e.g., self-ID, medical req.) | -              | Yes            |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n**Please Note: This analysis is still in progress.**\n\n### **Key Features of the Dataset**\n\nEach row represents a single country’s record for a specific year and includes information such as GDP per capita, education spending, and the legal status of various LGBTQ+ rights and protections.\n\n-   `year`: Year of observation\n\n-   `country`, `country-code`: Country name and ISO code\n\n-   `gdp-per-capita`: GDP per capita (constant international-\\$)\n\n-   `education-spending-gdp`: Government expenditure on education (% of GDP)\n\n-   `same-sex-marriage`: Legal status of same-sex marriage\n\n-   `lgbtq-censorship`: Whether LGBTQ+ topics are censored\n\n-   `employment-discrimination`: Laws against discrimination in employment\n\n-   `gender-affirming-care`: Legal and medical access to gender-affirming care\n\n-   `legal-gender`: Rights around legal gender marker change\n\n### **Purpose and Use Cases**\n\nThis dataset is designed to support analysis of:\n\n-   Global trends in LGBTQ+ rights over time\n\n-   Associations between legal protections and economic or educational indicators\n\n-   Regional disparities in access to gender-affirming care and anti-discrimination laws\n\n-   The relationship between policy environments and broader measures of social inclusion\n\n-   Temporal changes in legal recognition of same-sex marriage and gender identity\n\nIt enables cross-country comparisons and longitudinal studies using harmonized data from trusted open-access sources.\n\n## **Case Study**\n\n### **Objective**\n\n**Do countries with different levels of legal recognition for same-sex marriage also differ in terms of their economic development?**\n\nThis case study explores whether there are statistically significant differences in GDP per capita across countries grouped by their legal recognition of same-sex marriage:\n\n-   Legal (full marriage equality)\n-   Civil union or other partnership\n-   Not Recognized\n\nRather than implying causality, we use a one-way ANOVA (or an appropriate alternative based on assumption checks) to examine whether the average level of economic development differs significantly across these legal categories.\n\nTo do this, we apply one one-way ANOVA test (or an appropriate alternative test) to address the following question:\n\n-   Does marriage recognition status relate to national wealth?\\\n    Tested using GDP per capita as the response variable.\n\n### **Analysis**\n\n#### **Loading Libraries**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)  \nlibrary(patchwork)\nlibrary(knitr)\nlibrary(car)\nlibrary(FSA)\nlibrary(PMCMRplus)\n```\n:::\n\n\n#### **1. Data Cleaning & Processing**\n\n-   Dropped countries with missing values for key variables (`gdp-per-capita`, `education-spending-gdp`, `same-sex-marriage`)\n\n-   Converted text fields into consistent categories (e.g., combining “Unrecognized” and “Banned” into one group)\n\n-   Created a new factor variable: `marriage_group` . Based on our analytical goal which is comparing countries that formally recognize, partially recognize, or do not recognize same-sex unions at all. We created these three different levels for `marriage_group` filed.\n\n-   Filtered the dataset to include only one year per country to ensure independent observations across time\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_rights <- read_csv(\"../../data/clean/globalrights.csv\")\n# Get the last year overall in the dataset\nlast_year <- max(global_rights$year, na.rm = TRUE)\n##  map each of the levels in same sex marriage \n## into one of three standardized categories for analysis\ncleaned_df <- global_rights |>\n  filter(\n    year == last_year, \n    !is.na(`same-sex-marriage`),\n    !is.na(`gdp-per-capita`)\n  ) |>\n  mutate(marriage_group = case_when(\n    `same-sex-marriage` %in% c(\n      \"Legal\",\n      \"Foreign same-sex marriages recognized only\"\n    ) ~ \"Legal\",\n    \n    `same-sex-marriage` %in% c(\n      \"Civil union or other partnership\",\n      \"Unregistered cohabitation\"\n    ) ~ \"Civil Union or Partnership\",\n    \n    `same-sex-marriage` %in% c(\n      \"Banned\",\n      \"Unrecognized\",\n      \"Varies by region\"\n    ) ~ \"Not Recognized\",\n    \n    TRUE ~ \"Other\"\n  ))\n\nmessage(\"The dataset is filtered to the last year overall: \", last_year)\n```\n:::\n\n\n#### **2. Exploratory Data Analysis (EDA)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(cleaned_df, aes(x = marriage_group, y = `gdp-per-capita`, color = marriage_group)) +\n  geom_jitter(width = 0.2, alpha = 0.7) +\n  labs(\n    title = \"GDP per Capita by Marriage Recognition Group\",\n    x = \"Marriage Group\",\n    y = \"GDP per Capita (Intl $)\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](globalrights_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n**Boxplot of GDP per Capita/Education Spending by Marriage Group**\n\nThis shows the distribution of GDP per capita/Education Spending for each group of countries based on how they recognize same-sex marriage. It helps identify differences in economic and education spending status across the three groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# GDP per capita\ngdp_plot <- ggplot(cleaned_df, aes(x = marriage_group, y = `gdp-per-capita`)) +\n  geom_boxplot() +\n  labs(\n    title = \"GDP per Capita by Same-Sex Marriage Status\",\n    x = \"Marriage Group\",\n    y = \"GDP per Capita (Intl $)\"\n  ) +\n  theme_minimal()\n\n(gdp_plot)\n```\n\n::: {.cell-output-display}\n![](globalrights_files/figure-html/unnamed-chunk-4-1.png){width=768}\n:::\n:::\n\n::: {.cell}\n\n:::\n\nThe exploratory data analysis reveals that countries recognizing same-sex marriage (either fully or through civil unions) tend to have similar GDP per capita distributions, with overlapping interquartile ranges. In contrast, countries that do not recognize same-sex marriage show noticeably lower GDP per capita and exhibit no overlap with the other two groups, along with a higher number of outliers, indicating greater variability. For education spending, the distributions across all three groups are much closer, with less pronounced differences. While the Not Recognized group again shows some outliers, they are fewer compared to the GDP per capita distribution. This suggests that while economic wealth varies more strongly with legal recognition status, education investment appears relatively stable across groups.\n\n**Histogram of GDP per Capita (All Countries)**\n\nThese plots show the overall distributions of GDP per capita and education spending (% of GDP) across countries in the dataset. They allow us to assess the shape of each variable’s distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Histogram for GDP per Capita\nhist_gdp <- ggplot(cleaned_df, aes(x = `gdp-per-capita`)) +\n  geom_histogram(bins = 30, fill = \"skyblue\", color = \"white\") +\n  labs(\n    title = \"Distribution of GDP per Capita\",\n    x = \"GDP per Capita (Intl $)\",\n    y = \"Count of Countries\"\n  ) +\n  theme_minimal()\n\nhist_gdp \n```\n\n::: {.cell-output-display}\n![](globalrights_files/figure-html/unnamed-chunk-6-1.png){width=768}\n:::\n:::\n\n\nFrom the histograms, we observe that GDP per capita is right-skewed, indicating that most countries have relatively low to moderate GDP levels, with a smaller number of countries exhibiting much higher GDP per capita. This suggests economic wealth is concentrated in a few high-income countries.\\\n\n#### 3. Aim and hypotheses of ANOVA\n\nTo examine whether economic indicators differ across countries based on their legal recognition of same-sex marriage, we conduct two one-way ANOVA tests. Each test evaluates whether the mean value of a numeric variable varies significantly across the three legal categories: Legal, Civil Union, and Not Recognized.\n\n**1. ANOVA for GDP per Capita**\n\nWe test whether countries with different legal recognition statuses have significantly different mean GDP per capita.\n\n-   Null Hypothesis (H₀):\\\n    $$\n    \\mu_{\\text{GDP}}(\\text{Legal}) = \\mu_{\\text{GDP}}(\\text{Civil Union}) = \\mu_{\\text{GDP}}(\\text{Not Recognized})\n    $$\n\n-   Alternative Hypothesis (Hₐ):\\\n    $$\n    \\text{At least one pair of group means for GDP per capita is different.}\n    $$\n\nThese tests help determine whether economic wealth or public investment in education is associated with how countries legally recognize same-sex marriage.\n\n#### **4. Underlying assumptions of ANOVA**\n\n##### **1. Independence of Observations**\n\n-   Observations within and across groups must be independent.\n-   In our case, this means that each country-year observation is independent of others.\n-   This assumption is typically satisfied by the design of the dataset if no country appears more than once per year and data points are not clustered.\n-   Please note that dataset includes only one year per country to ensure independent observations across time\n\n\n::: {.cell}\n\n```{.r .cell-code}\nduplicates <- cleaned_df |>\n  count(country, year, name = \"count\") |>\n  filter(count > 1) |>\n  arrange(desc(count), country, year)\n\nif (nrow(duplicates) == 0) {\n  print(\"No duplicate country-year combinations found. Independence assumption is satisfied.\")\n} else {\n  print(\"Some countries appear more than once in the same year. See the table below:\")\n  duplicates |>\n    rename(\n      `Country` = country,\n      `Year` = year,\n      `Number of Entries` = count\n    ) |>\n    kable(\n      caption = \"Duplicate Country-Year Combinations\",\n      align = \"lcc\"\n    )\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"No duplicate country-year combinations found. Independence assumption is satisfied.\"\n```\n\n\n:::\n:::\n\n\n##### **2. Normality of Residuals**\n\n-   The residuals within each group (i.e., within Legal, Civil Union, and Not Recognized) should be approximately normally distributed.\n-   We will assess this assumption using:\n    -   Histogram or Q-Q plots of the residuals\n    -   Shapiro-Wilk test for normality within each group\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# GDP per capita - residuals within groups\ngdp_residuals <- cleaned_df |>\n  group_by(marriage_group) |>\n  mutate(gdp_resid = `gdp-per-capita` - mean(`gdp-per-capita`, na.rm = TRUE)) |>\n  ungroup()\n```\n:::\n\n\n**Q-Q Plots for GDP Residuals**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gdp_residuals, aes(sample = gdp_resid)) +\n  stat_qq(color = \"skyblue\") +         \n  stat_qq_line(color = \"black\") +      \n  facet_wrap(~marriage_group) +\n  labs(\n    title = \"Q-Q Plot of GDP per Capita Residuals\",\n    x = \"Theoretical Quantiles\",\n    y = \"Sample Quantiles\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](globalrights_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Shapiro-Wilk Test for Normality (All Groups)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# GDP residuals by group\ngdp_shapiro <- gdp_residuals |>\n  group_by(marriage_group) |>\n  summarise(\n    p_value = shapiro.test(gdp_resid)$p.value,\n    .groups = \"drop\"\n  ) |>\n  rename(`Group` = marriage_group, `GDP Residuals p-value` = p_value)\nknitr::kable(\n  gdp_shapiro,\n  caption = \"Shapiro-Wilk Test Results for Normality of GDP Residuals\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Shapiro-Wilk Test Results for Normality of GDP Residuals\n\n|Group                      | GDP Residuals p-value|\n|:--------------------------|---------------------:|\n|Civil Union or Partnership |             0.0733833|\n|Legal                      |             0.0726414|\n|Not Recognized             |             0.0000001|\n\n\n:::\n:::\n\n\nFor GDP per capita, the Q-Q plot shows a clear deviation from the 45-degree line in the Not Recognized group, indicating that the residuals are not normally distributed. This is confirmed by the Shapiro-Wilk test, which returns p-values below 0.001 for all three marriage groups, leading us to reject the assumption of normality. As a result, the normality assumption for ANOVA is not satisfied for GDP per capita, and alternative approaches such as a log transformation, Welch’s ANOVA, or the Kruskal–Wallis test may be more appropriate.\n\n##### **3. Homogeneity of Variances (Homoscedasticity)**\n\n-   The variance of the response variable should be similar across all groups.\n-   We will check this using:\n    -   Levene’s Test or Bartlett’s Test for equality of variances\n    -   Visual inspection via boxplots for any substantial differences in spread\n\n**Levene's and Bartlett's Test for GDP per Capita**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# GDP per capita\ngdp_levene <- leveneTest(`gdp-per-capita` ~ marriage_group, data = cleaned_df)\ngdp_bartlett <- bartlett.test(`gdp-per-capita` ~ marriage_group, data = cleaned_df)\n```\n:::\n\n\n**The Results**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhomogeneity_results <- tibble::tibble(\n  Variable = c(\"GDP per Capita\", \"GDP per Capita\"),\n  Test = c(\"Levene's Test\", \"Bartlett's Test\"),\n  `Test Statistic` = c(\n    gdp_levene$`F value`[1],\n    gdp_bartlett$statistic\n  ),\n  `p-value` = c(\n    gdp_levene$`Pr(>F)`[1],\n    gdp_bartlett$p.value\n  )\n)\n\nknitr::kable(\n  homogeneity_results,\n  caption = \"Homogeneity of Variances for GDP per Capita: Levene’s and Bartlett’s Tests\",\n  digits = 4\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Homogeneity of Variances for GDP per Capita: Levene’s and Bartlett’s Tests\n\n|Variable       |Test            | Test Statistic| p-value|\n|:--------------|:---------------|--------------:|-------:|\n|GDP per Capita |Levene's Test   |         1.8638|  0.1618|\n|GDP per Capita |Bartlett's Test |         6.5058|  0.0387|\n\n\n:::\n:::\n\n\nFor GDP per capita, Levene’s test suggests that the assumption of equal variances is not violated (p = 0.1618), while Bartlett’s test indicates a violation (p = 0.0387). Since Bartlett’s test is more sensitive to deviations from normality, and the two tests disagree, caution should be used when interpreting the homogeneity of variances assumption for this variable.\n\n#### **5. Data Transformation (Log Scale)**\n\nWe applied a log transformation to GDP per capita and education spending to address violations of ANOVA assumptions. This transformation helps reduce right skewness and stabilize variance across groups, making the data more suitable for parametric tests like Welch’s ANOVA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncleaned_df <- cleaned_df |>\n  mutate(\n    log_gdp = log(`gdp-per-capita`),\n    log_edu = log(`education-spending-gdp`)\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(cleaned_df, aes(sample = log_gdp)) +\n stat_qq(color = \"skyblue\") +         \n  stat_qq_line(color = \"black\") + \n  facet_wrap(~marriage_group) +\n  labs(\n    title = \"Q-Q Plot of Log(GDP per Capita) Residuals by Group\",\n    x = \"Theoretical Quantiles\",\n    y = \"Sample Quantiles\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](globalrights_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n**Shapiro-Wilk Test for Normality (All Groups) after Log Scale**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngdp_shapiro_log <- cleaned_df |>\n  group_by(marriage_group) |>\n  summarise(\n    p_value = shapiro.test(log_gdp)$p.value,\n    .groups = \"drop\"\n  ) |>\n  rename(`Group` = marriage_group, `log(GDP) p-value` = p_value)\n\nknitr::kable(\n  gdp_shapiro_log,\n  caption = \"Shapiro-Wilk Test Results for Normality of Log-Transformed GDP per Capita\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Shapiro-Wilk Test Results for Normality of Log-Transformed GDP per Capita\n\n|Group                      | log(GDP) p-value|\n|:--------------------------|----------------:|\n|Civil Union or Partnership |        0.0014443|\n|Legal                      |        0.0850579|\n|Not Recognized             |        0.4244092|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlevene_log_gdp <- leveneTest(log_gdp ~ marriage_group, data = cleaned_df)\nbartlett_log_gdp <- bartlett.test(log_gdp ~ marriage_group, data = cleaned_df)\n\nlog_gdp_variance_tests <- tibble::tibble(\n  Variable = c(\"Log GDP per Capita\", \"Log GDP per Capita\"),\n  Test = c(\"Levene’s Test\", \"Bartlett’s Test\"),\n  `Test Statistic` = c(\n    levene_log_gdp$`F value`[1],\n    bartlett_log_gdp$statistic\n  ),\n  `p-value` = c(\n    levene_log_gdp$`Pr(>F)`[1],\n    bartlett_log_gdp$p.value\n  )\n)\n\nknitr::kable(\n  log_gdp_variance_tests,\n  caption = \"Homogeneity of Variances for Log GDP per Capita: Levene’s and Bartlett’s Tests\",\n  digits = 4\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Homogeneity of Variances for Log GDP per Capita: Levene’s and Bartlett’s Tests\n\n|Variable           |Test            | Test Statistic| p-value|\n|:------------------|:---------------|--------------:|-------:|\n|Log GDP per Capita |Levene’s Test   |         9.7838|   2e-04|\n|Log GDP per Capita |Bartlett’s Test |        17.4628|   2e-04|\n\n\n:::\n:::\n\n\nEven after applying the log transformation, both Levene’s test (p = 0.0002) and Bartlett’s test (p = 0.0002) for log GDP per capita return very small p-values. This indicates that the assumption of equal variances is still violated.\n\nTherefore, standard ANOVA remains inappropriate for analyzing differences in log GDP per capita across groups, and a more robust alternative should be considered.\n\n#### **6. Alternative Approaches to ANOVA**\n\n##### **1. GDP per Capita: Kruskal–Wallis Test**\n\nSince the assumptions of normality and homogeneity of variances were both violated for GDP per capita, we applied the Kruskal–Wallis test, a non-parametric alternative to one-way ANOVA.\n\nThis test compares the distributions of the response variable across groups, rather than their means, and does not require normality or equal variances.\n\nWe chose this test because it is robust and appropriate when ANOVA assumptions are not met, particularly in the presence of skewed data and unequal variances.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngdp_kw <- kruskal.test(`gdp-per-capita` ~ marriage_group, data = cleaned_df)\n```\n:::\n\n\nAnd this is our final result :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinal_gdp_test_result <- tibble::tibble(\n  Variable = \"GDP per Capita\",\n  Test = \"Kruskal–Wallis\",\n  `Test Statistic` = gdp_kw$statistic,\n  `p-value` = gdp_kw$p.value\n)\n\nknitr::kable(\n  final_gdp_test_result,\n  caption = \"Final Test Result for GDP per Capita: Kruskal–Wallis Test\",\n  digits = 4,\n  align = \"lcc\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Final Test Result for GDP per Capita: Kruskal–Wallis Test\n\n|Variable       |      Test      | Test Statistic |p-value |\n|:--------------|:--------------:|:--------------:|:-------|\n|GDP per Capita | Kruskal–Wallis |    37.6841     |0       |\n\n\n:::\n:::\n\n\nFor GDP per capita, the Kruskal–Wallis test returned a large test statistic (37.6841) with a p-value of 0, indicating a statistically significant difference in distributions across the three marriage recognition groups.\n\nSince the Kruskal–Wallis test does not require normality or equal variances, this result provides strong evidence that at least one group differs in GDP distribution. This supports the conclusion that GDP per capita is associated with the legal recognition of same-sex marriage across countries.\n\n#### **7. Post-hoc Tests**\n\nWhile our main tests (Kruskal–Wallis for GDP per capita and Welch’s ANOVA for education spending) showed that there are statistically significant differences across the marriage recognition groups, they do not specify which specific group pairs differ from each other. To gain a clearer understanding of where these differences lie such as whether countries recognizing same-sex marriage differ significantly from those offering only civil unions or no recognition we conducted post-hoc test.\n\n##### **1. Post-hoc Test for GDP per Capita**\n\nSince we used the Kruskal–Wallis test (a non-parametric method) for GDP per capita, we followed it with Dunn’s test for post-hoc comparisons. The Kruskal–Wallis test tells us whether there's a difference in distributions among the groups, but it does not tell us which pairs of groups differ. Dunn’s test fills that gap. What is Dunn’s Test? Dunn’s test performs pairwise comparisons between all levels of the grouping variable (in this case, marriage_group) using ranked data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngdp_posthoc <- dunnTest(`gdp-per-capita` ~ marriage_group, data = cleaned_df, method = \"bonferroni\")\n\ngdp_posthoc$res |>\n  mutate(p.adj = round(P.adj, 4)) |>\n  select(Comparison, `Z Statistic` = Z, `p-value` = p.adj) |>\n  kable(\n    caption = \"Dunn’s Post-hoc Test for GDP per Capita (Bonferroni Correction)\",\n    align = \"lcc\",\n    digits = 4\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Dunn’s Post-hoc Test for GDP per Capita (Bonferroni Correction)\n\n|Comparison                                  | Z Statistic | p-value |\n|:-------------------------------------------|:-----------:|:-------:|\n|Civil Union or Partnership - Legal          |   -1.8689   | 0.1849  |\n|Civil Union or Partnership - Not Recognized |   2.8144    | 0.0147  |\n|Legal - Not Recognized                      |   6.0984    | 0.0000  |\n\n\n:::\n:::\n\n\nDunn’s post-hoc test shows a significant difference in GDP per capita between countries that do not recognize same-sex marriage and those that do, either through legal marriage or civil unions. However, there is no significant difference between countries offering legal marriage and those offering civil unions, suggesting the economic gap lies primarily between recognition and non-recognition.\n\n### **Discussion**\n\nCountries that differ in their legal recognition of same-sex marriage also show significant differences in GDP per capita. Initial ANOVA assumption checks revealed clear violations of normality and homogeneity of variances for this variable. Even after applying a log transformation, these issues persisted, making standard ANOVA inappropriate.\n\nAs a result, we used the Kruskal–Wallis test, a non-parametric alternative that does not assume normality or equal variances. The test revealed highly significant group-level differences. Post-hoc analysis showed that countries not recognizing same-sex marriage have significantly lower GDP per capita than those offering civil unions or legal marriage, while no significant difference was found between the latter two.\n\nThese findings suggest a strong association between economic development and the legal recognition of same-sex marriage, with more economically developed countries being more likely to adopt inclusive legal frameworks.\n\n\n\n## Attribution\n\nThis analysis uses data compiled and curated from **Our World in Data**, an open-access initiative that aggregates global development indicators. The variables used in this analysis include economic and policy-related measures across 91 countries from 2000 to 2023.\n\nData sources include:\n\n- **GDP per Capita**: [Our World in Data – Economic Growth](https://ourworldindata.org/economic-growth)  \n- **Education Spending (% of GDP)**: [Our World in Data – Education Expenditure](https://ourworldindata.org/financing-education)  \n- **LGBTQ+ Rights Indicators**:  \n  - [Same-Sex Marriage Laws](https://ourworldindata.org/lgbt-rights)  \n  - [LGBTQ+ Censorship](https://ourworldindata.org/lgbt-rights)  \n  - [Employment Discrimination Protections](https://ourworldindata.org/lgbt-rights)  \n  - [Gender-Affirming Care Access](https://ourworldindata.org/lgbt-rights)  \n  - [Legal Gender Recognition](https://ourworldindata.org/lgbt-rights)  \n\nAll data is used under the terms of the **Creative Commons BY license**. Please refer to [Our World in Data – Licensing](https://ourworldindata.org/licensing) for more details.\n\n> **Citation**:  \n> Our World in Data. Various datasets compiled and maintained by the Global Change Data Lab.  \n> [https://ourworldindata.org](https://ourworldindata.org)",
    "supporting": [
      "globalrights_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}